services:
  tool:
    image: shaug/m4bber:main
    # build: .
    container_name: m4bber
    volumes:
      - ./audiobooks:/audiobooks
    environment:
      - M4BBER_BACKUP_DIR=backups
    command:
      - --chapter-detection